// <auto-generated>
// Generated by tools/operations/generate.py from src/Idrak.Abstraction/Devices/Backend.cs; do not edit.
// </auto-generated>
// Copyright (c) 2026 Ahmed Seada
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

#nullable enable

using Idrak.Abstraction.Devices;

namespace Idrak.Abstraction.Operations;

/// <summary>The index of each operation in a device's kernel slots (see <see cref="Ops"/>).</summary>
internal static class OperationIndex
{
    public const int Fill = 0;
    public const int Unary = 1;
    public const int UnaryBackward = 2;
    public const int Binary = 3;
    public const int ExtremumBackward = 4;
    public const int Pow = 5;
    public const int PowBackward = 6;
    public const int Clamp = 7;
    public const int ClampBackward = 8;
    public const int Where = 9;
    public const int WhereBackward = 10;
    public const int Affine = 11;
    public const int Axpy = 12;
    public const int MulAdd = 13;
    public const int AddRowVector = 14;
    public const int SumRows = 15;
    public const int Sum = 16;
    public const int AxpyAt = 17;
    public const int AddBroadcastScalar = 18;
    public const int PackedMatMulLarge = 19;
    public const int PackedMatMulGated = 20;
    public const int PackedMatMulAddRmsNorm = 21;
    public const int PackedMatMulMany = 22;
    public const int PackedMatMulGatedPair = 23;
    public const int MatMulMany = 24;
    public const int MatMulBias = 25;
    public const int MatMulLowRank = 26;
    public const int BFloat16TransposedMatMul = 27;
    public const int Float8QuantizeWeight = 28;
    public const int Float8MatMul = 29;
    public const int PackedMatMulLowRank = 30;
    public const int GemmStrided = 31;
    public const int AttentionStrided = 32;
    public const int AttentionStridedBackward = 33;
    public const int SumColumns = 34;
    public const int AddDropout = 35;
    public const int BatchedMatMul = 36;
    public const int Softmax = 37;
    public const int SoftmaxBackward = 38;
    public const int ArgMax = 39;
    public const int ClassMatch = 40;
    public const int NormStats = 41;
    public const int NormApply = 42;
    public const int NormBackward = 43;
    public const int GroupScaleShift = 44;
    public const int GroupReduce = 45;
    public const int InvSqrt = 46;
    public const int Gather = 47;
    public const int GatherBFloat16 = 48;
    public const int OneHot = 49;
    public const int ScatterAdd = 50;
    public const int Im2Col = 51;
    public const int Col2Im = 52;
    public const int MaxPool = 53;
    public const int MaxPoolBackward = 54;
    public const int MaxPoolBackward2 = 55;
    public const int Permute = 56;
    public const int SumAxis = 57;
    public const int BroadcastAxis = 58;
    public const int SgdStep = 59;
    public const int AdamStep = 60;
    public const int AdamStep8Bit = 61;
    public const int SumSquares = 62;
    public const int FusedAdamW = 63;
    public const int ClipFactor = 64;
    public const int Dropout = 65;
    public const int DropoutBackward = 66;
    public const int ScaleMaskSoftmax = 67;
    public const int LayerNormFused = 68;
    public const int LayerNormTrain = 69;
    public const int LayerNormBackward = 70;
    public const int BiasGelu = 71;
    public const int Int8MatMul = 72;
    public const int BFloat16MatMul = 73;
    public const int BFloat16Dequantize = 74;
    public const int PackBFloat16 = 75;
    public const int Int8Dequantize = 76;
    public const int Int4MatMul = 77;
    public const int Int4Dequantize = 78;
    public const int RmsNorm = 79;
    public const int RmsNormBackward = 80;
    public const int Rope = 81;
    public const int RmsNormAffine = 82;
    public const int AddRmsNormAffine = 83;
    public const int RmsNormRope = 84;
    public const int RmsNormRopePair = 85;
    public const int NormRopeHeads = 86;
    public const int SoftmaxCrossEntropyRows = 87;
    public const int GatedActivation = 88;
    public const int GatedActivationBackward = 89;
    public const int GatedActivationPacked = 90;
    public const int GatedActivationBackwardPacked = 91;
    public const int KeyValueWriteInt8 = 92;
    public const int AttentionScoresInt8 = 93;
    public const int AttentionContextInt8 = 94;
    public const int AttentionDecode = 95;
    public const int AttentionInt8 = 96;
    public const int AttentionBFloat16 = 97;
    public const int KeyValueWriteBFloat16 = 98;
    public const int AttentionTiledBackward = 99;
    public const int AttentionSegmented = 100;
    public const int AttentionRows = 101;
    public const int AttentionSegmentedBackward = 102;
    public const int AttentionTiled = 103;
    public const int DecoderMask = 104;
    public const int KeyValueWrite = 105;
    public const int SampleRows = 106;
    public const int PenalizeRows = 107;
    public const int HistoryPush = 108;

    /// <summary>The number of operations.</summary>
    public const int Count = 109;
}

/// <summary>The kernel delegate of each operation: the device's backend, then the operation's arguments.</summary>
internal static class OperationKernels
{
    /// <summary>A kernel for <see cref="Ops.Fill"/>.</summary>
    public delegate void Fill(Backend backend, Storage y, int n, float value);

    /// <summary>A kernel for <see cref="Ops.Unary"/>.</summary>
    public delegate void Unary(Backend backend, UnaryOp op, Storage x, Storage y, int n);

    /// <summary>A kernel for <see cref="Ops.UnaryBackward"/>.</summary>
    public delegate void UnaryBackward(Backend backend, UnaryOp op, Storage x, Storage y, Storage dy, Storage dx, int n);

    /// <summary>A kernel for <see cref="Ops.Binary"/>.</summary>
    public delegate void Binary(Backend backend, BinaryOp op, Storage a, Storage b, Storage c, int n);

    /// <summary>A kernel for <see cref="Ops.ExtremumBackward"/>.</summary>
    public delegate void ExtremumBackward(Backend backend, BinaryOp op, Storage a, Storage b, Storage dy, Storage? da, Storage? db, int n);

    /// <summary>A kernel for <see cref="Ops.Pow"/>.</summary>
    public delegate void Pow(Backend backend, Storage x, Storage y, int n, float exponent);

    /// <summary>A kernel for <see cref="Ops.PowBackward"/>.</summary>
    public delegate void PowBackward(Backend backend, Storage x, Storage dy, Storage dx, int n, float exponent);

    /// <summary>A kernel for <see cref="Ops.Clamp"/>.</summary>
    public delegate void Clamp(Backend backend, Storage x, Storage y, int n, float min, float max);

    /// <summary>A kernel for <see cref="Ops.ClampBackward"/>.</summary>
    public delegate void ClampBackward(Backend backend, Storage x, Storage dy, Storage dx, int n, float min, float max);

    /// <summary>A kernel for <see cref="Ops.Where"/>.</summary>
    public delegate void Where(Backend backend, Storage condition, Storage a, Storage b, Storage y, int n);

    /// <summary>A kernel for <see cref="Ops.WhereBackward"/>.</summary>
    public delegate void WhereBackward(Backend backend, Storage condition, Storage dy, Storage? da, Storage? db, int n);

    /// <summary>A kernel for <see cref="Ops.Affine"/>.</summary>
    public delegate void Affine(Backend backend, Storage x, Storage y, int n, float alpha, float beta);

    /// <summary>A kernel for <see cref="Ops.Axpy"/>.</summary>
    public delegate void Axpy(Backend backend, Storage x, Storage y, int n, float alpha);

    /// <summary>A kernel for <see cref="Ops.MulAdd"/>.</summary>
    public delegate void MulAdd(Backend backend, Storage a, Storage b, Storage c, int n);

    /// <summary>A kernel for <see cref="Ops.AddRowVector"/>.</summary>
    public delegate void AddRowVector(Backend backend, Storage a, Storage v, Storage c, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.SumRows"/>.</summary>
    public delegate void SumRows(Backend backend, Storage x, Storage y, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.Sum"/>.</summary>
    public delegate void Sum(Backend backend, Storage x, Storage result, int n, float scale);

    /// <summary>A kernel for <see cref="Ops.AxpyAt"/>.</summary>
    public delegate void AxpyAt(Backend backend, Storage x, Storage y, int offset, float alpha);

    /// <summary>A kernel for <see cref="Ops.AddBroadcastScalar"/>.</summary>
    public delegate void AddBroadcastScalar(Backend backend, Storage s, Storage y, int n, float scale);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulLarge"/>.</summary>
    public delegate bool PackedMatMulLarge(Backend backend, PackedFormat format, Storage x, Storage packed, Storage? scales, Storage y, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulGated"/>.</summary>
    public delegate bool PackedMatMulGated(Backend backend, PackedFormat format, int activation, Storage gate, Storage up, Storage packed, Storage? scales, Storage y, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulAddRmsNorm"/>.</summary>
    public delegate bool PackedMatMulAddRmsNorm(Backend backend, PackedFormat format, Storage x, Storage packed, Storage? scales, Storage y, int m, int n, int k, Storage residual, Storage sum, Storage gain, Storage normalized, float eps, float offset);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulMany"/>.</summary>
    public delegate bool PackedMatMulMany(Backend backend, PackedFormat format, Storage x, int m, int k, ReadOnlySpan<(Storage Packed, Storage? Scales, Storage? Bias, Storage Output, int Columns)> products);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulGatedPair"/>.</summary>
    public delegate bool PackedMatMulGatedPair(Backend backend, PackedFormat format, int activation, Storage x, int m, int k, ReadOnlySpan<(Storage Packed, Storage? Scales, Storage? Bias, Storage Output, int Columns)> products, Storage hidden);

    /// <summary>A kernel for <see cref="Ops.MatMulMany"/>.</summary>
    public delegate void MatMulMany(Backend backend, Storage a, int m, int k, ReadOnlySpan<(Storage Weight, Storage? Bias, Storage Output, int Columns)> products);

    /// <summary>A kernel for <see cref="Ops.MatMulBias"/>.</summary>
    public delegate bool MatMulBias(Backend backend, Storage a, Storage b, Storage bias, Storage c, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.MatMulLowRank"/>.</summary>
    public delegate bool MatMulLowRank(Backend backend, Storage a, Storage b, Storage c, int m, int n, int k, bool transB, float beta, Storage u, Storage v, int rank);

    /// <summary>A kernel for <see cref="Ops.BFloat16TransposedMatMul"/>.</summary>
    public delegate bool BFloat16TransposedMatMul(Backend backend, Storage a, Storage packed, Storage c, int m, int n, int k, float beta, Storage? u, Storage? v, int rank);

    /// <summary>A kernel for <see cref="Ops.Float8QuantizeWeight"/>.</summary>
    public delegate bool Float8QuantizeWeight(Backend backend, Storage w, int k, int n, Storage values, Storage scales);

    /// <summary>A kernel for <see cref="Ops.Float8MatMul"/>.</summary>
    public delegate bool Float8MatMul(Backend backend, Storage x, int m, int k, Storage values, Storage scales, int n, Storage y, float beta);

    /// <summary>A kernel for <see cref="Ops.PackedMatMulLowRank"/>.</summary>
    public delegate bool PackedMatMulLowRank(Backend backend, PackedFormat format, Storage x, int m, int k, ReadOnlySpan<(Storage Packed, Storage? Scales, Storage Output, int Columns, Storage U, Storage V)> products, int rank);

    /// <summary>A kernel for <see cref="Ops.GemmStrided"/>.</summary>
    public delegate bool GemmStrided(Backend backend, Storage a, long aOffset, int lda, bool transA, Storage b, long bOffset, int ldb, bool transB, Storage c, long cOffset, int ldc, int m, int n, int k, float beta, Storage? bias, GemmEpilogue epilogue, Storage? aux, long auxOffset);

    /// <summary>A kernel for <see cref="Ops.AttentionStrided"/>.</summary>
    public delegate bool AttentionStrided(Backend backend, Storage q, long qOffset, Storage k, long kOffset, Storage v, long vOffset, int qRow, int kRow, Storage y, Storage? logSumExp, int batch, int kvHeads, int group, int steps, int dim, float scale);

    /// <summary>A kernel for <see cref="Ops.AttentionStridedBackward"/>.</summary>
    public delegate bool AttentionStridedBackward(Backend backend, Storage q, long qOffset, Storage k, long kOffset, Storage v, long vOffset, int qRow, int kRow, Storage y, Storage logSumExp, Storage dOutput, Storage dq, long dqOffset, Storage dk, long dkOffset, Storage dv, long dvOffset, int batch, int kvHeads, int group, int steps, int dim, float scale);

    /// <summary>A kernel for <see cref="Ops.SumColumns"/>.</summary>
    public delegate void SumColumns(Backend backend, Storage x, long offset, int ld, Storage y, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.AddDropout"/>.</summary>
    public delegate void AddDropout(Backend backend, Storage residual, Storage x, Storage output, int n, float p, uint seed);

    /// <summary>A kernel for <see cref="Ops.BatchedMatMul"/>.</summary>
    public delegate void BatchedMatMul(Backend backend, Storage a, Storage b, Storage c, int batch, int m, int n, int k, bool transA, bool transB, float beta);

    /// <summary>A kernel for <see cref="Ops.Softmax"/>.</summary>
    public delegate void Softmax(Backend backend, Storage x, Storage y, int rows, int cols, bool log);

    /// <summary>A kernel for <see cref="Ops.SoftmaxBackward"/>.</summary>
    public delegate void SoftmaxBackward(Backend backend, Storage y, Storage dy, Storage dx, int rows, int cols, bool log);

    /// <summary>A kernel for <see cref="Ops.ArgMax"/>.</summary>
    public delegate void ArgMax(Backend backend, Storage x, Storage y, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.ClassMatch"/>.</summary>
    public delegate void ClassMatch(Backend backend, Storage predictions, Storage targets, Storage y, int rows, int cols, float threshold);

    /// <summary>A kernel for <see cref="Ops.NormStats"/>.</summary>
    public delegate void NormStats(Backend backend, Storage x, Storage mean, Storage variance, Storage invStd, int outer, int groups, int inner, float eps);

    /// <summary>A kernel for <see cref="Ops.NormApply"/>.</summary>
    public delegate void NormApply(Backend backend, Storage x, Storage mean, Storage invStd, Storage y, int outer, int groups, int inner);

    /// <summary>A kernel for <see cref="Ops.NormBackward"/>.</summary>
    public delegate void NormBackward(Backend backend, Storage dxhat, Storage xhat, Storage sum1, Storage sum2, Storage invStd, Storage dx, int outer, int groups, int inner);

    /// <summary>A kernel for <see cref="Ops.GroupScaleShift"/>.</summary>
    public delegate void GroupScaleShift(Backend backend, Storage x, Storage? scale, Storage? shift, Storage y, int n, int groups, int inner, bool accumulate);

    /// <summary>A kernel for <see cref="Ops.GroupReduce"/>.</summary>
    public delegate void GroupReduce(Backend backend, Storage a, Storage? b, Storage sumA, Storage? sumAB, int outer, int groups, int inner);

    /// <summary>A kernel for <see cref="Ops.InvSqrt"/>.</summary>
    public delegate void InvSqrt(Backend backend, Storage x, Storage y, int n, float eps);

    /// <summary>A kernel for <see cref="Ops.Gather"/>.</summary>
    public delegate void Gather(Backend backend, Storage table, Storage indices, Storage y, int count, int dim, int vocabulary);

    /// <summary>A kernel for <see cref="Ops.GatherBFloat16"/>.</summary>
    public delegate void GatherBFloat16(Backend backend, Storage packed, Storage indices, Storage y, int count, int dim, int vocabulary);

    /// <summary>A kernel for <see cref="Ops.OneHot"/>.</summary>
    public delegate void OneHot(Backend backend, Storage indices, Storage y, int count, int classes);

    /// <summary>A kernel for <see cref="Ops.ScatterAdd"/>.</summary>
    public delegate void ScatterAdd(Backend backend, Storage dy, Storage indices, Storage dtable, int count, int dim, int vocabulary);

    /// <summary>A kernel for <see cref="Ops.Im2Col"/>.</summary>
    public delegate void Im2Col(Backend backend, Storage x, Storage cols, in ConvGeometry g);

    /// <summary>A kernel for <see cref="Ops.Col2Im"/>.</summary>
    public delegate void Col2Im(Backend backend, Storage dcols, Storage dx, in ConvGeometry g);

    /// <summary>A kernel for <see cref="Ops.MaxPool"/>.</summary>
    public delegate void MaxPool(Backend backend, Storage x, Storage y, Storage argmax, in ConvGeometry g);

    /// <summary>A kernel for <see cref="Ops.MaxPoolBackward"/>.</summary>
    public delegate void MaxPoolBackward(Backend backend, Storage dy, Storage argmax, Storage dx, int count);

    /// <summary>A kernel for <see cref="Ops.MaxPoolBackward2"/>.</summary>
    public delegate void MaxPoolBackward2(Backend backend, Storage dy, Storage argmax, Storage dx, in ConvGeometry g);

    /// <summary>A kernel for <see cref="Ops.Permute"/>.</summary>
    public delegate void Permute(Backend backend, Storage x, Storage y, ReadOnlySpan<int> outShape, ReadOnlySpan<int> inStrides, bool accumulate);

    /// <summary>A kernel for <see cref="Ops.SumAxis"/>.</summary>
    public delegate void SumAxis(Backend backend, Storage x, Storage y, int outer, int dim, int inner, float scale, bool accumulate);

    /// <summary>A kernel for <see cref="Ops.BroadcastAxis"/>.</summary>
    public delegate void BroadcastAxis(Backend backend, Storage dy, Storage dx, int outer, int dim, int inner, float scale);

    /// <summary>A kernel for <see cref="Ops.SgdStep"/>.</summary>
    public delegate void SgdStep(Backend backend, Storage p, Storage g, Storage? v, int n, float lr, float momentum);

    /// <summary>A kernel for <see cref="Ops.AdamStep"/>.</summary>
    public delegate void AdamStep(Backend backend, Storage p, Storage g, Storage m, Storage v, int n, float lr, float beta1, float beta2, float eps);

    /// <summary>A kernel for <see cref="Ops.AdamStep8Bit"/>.</summary>
    public delegate void AdamStep8Bit(Backend backend, Storage p, Storage g, Storage m, Storage v, Storage absMax, Storage map, int n, float lr, float beta1, float beta2, float eps, float gradientScale, float decay);

    /// <summary>A kernel for <see cref="Ops.SumSquares"/>.</summary>
    public delegate void SumSquares(Backend backend, Storage x, Storage total, int n);

    /// <summary>A kernel for <see cref="Ops.FusedAdamW"/>.</summary>
    public delegate bool FusedAdamW(Backend backend, ReadOnlySpan<(Storage P, Storage G, Storage M, Storage V, int N)> tensors, ref IDisposable? cache, float maxNorm, float lr, float decay, float beta1, float beta2, float eps, bool zeroGradients);

    /// <summary>A kernel for <see cref="Ops.ClipFactor"/>.</summary>
    public delegate void ClipFactor(Backend backend, Storage sumSquares, Storage factor, float maxNorm);

    /// <summary>A kernel for <see cref="Ops.Dropout"/>.</summary>
    public delegate void Dropout(Backend backend, Storage x, Storage y, int n, float p, uint seed);

    /// <summary>A kernel for <see cref="Ops.DropoutBackward"/>.</summary>
    public delegate void DropoutBackward(Backend backend, Storage dy, Storage dx, int n, float p, uint seed);

    /// <summary>A kernel for <see cref="Ops.ScaleMaskSoftmax"/>.</summary>
    public delegate void ScaleMaskSoftmax(Backend backend, Storage x, Storage? mask, Storage y, int rows, int cols, int maskRows, float scale);

    /// <summary>A kernel for <see cref="Ops.LayerNormFused"/>.</summary>
    public delegate void LayerNormFused(Backend backend, Storage x, Storage gamma, Storage beta, Storage y, int rows, int cols, float eps);

    /// <summary>A kernel for <see cref="Ops.LayerNormTrain"/>.</summary>
    public delegate void LayerNormTrain(Backend backend, Storage x, Storage gamma, Storage beta, Storage y, Storage stats, int rows, int cols, float eps);

    /// <summary>A kernel for <see cref="Ops.LayerNormBackward"/>.</summary>
    public delegate void LayerNormBackward(Backend backend, Storage x, Storage gamma, Storage dy, Storage stats, Storage? dx, Storage? dgamma, Storage? dbeta, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.BiasGelu"/>.</summary>
    public delegate void BiasGelu(Backend backend, Storage x, Storage bias, Storage y, int n, int cols);

    /// <summary>A kernel for <see cref="Ops.Int8MatMul"/>.</summary>
    public delegate void Int8MatMul(Backend backend, Storage x, Storage q, Storage scales, Storage y, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.BFloat16MatMul"/>.</summary>
    public delegate void BFloat16MatMul(Backend backend, Storage x, Storage packed, Storage y, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.BFloat16Dequantize"/>.</summary>
    public delegate void BFloat16Dequantize(Backend backend, Storage packed, Storage w, int k, int n);

    /// <summary>A kernel for <see cref="Ops.PackBFloat16"/>.</summary>
    public delegate void PackBFloat16(Backend backend, Storage x, Storage packed, int n);

    /// <summary>A kernel for <see cref="Ops.Int8Dequantize"/>.</summary>
    public delegate void Int8Dequantize(Backend backend, Storage q, Storage scales, Storage w, int k, int n);

    /// <summary>A kernel for <see cref="Ops.Int4MatMul"/>.</summary>
    public delegate void Int4MatMul(Backend backend, Storage x, Storage q, Storage scales, Storage y, int m, int n, int k);

    /// <summary>A kernel for <see cref="Ops.Int4Dequantize"/>.</summary>
    public delegate void Int4Dequantize(Backend backend, Storage q, Storage scales, Storage w, int k, int n);

    /// <summary>A kernel for <see cref="Ops.RmsNorm"/>.</summary>
    public delegate void RmsNorm(Backend backend, Storage x, Storage y, Storage inv, int rows, int cols, float eps);

    /// <summary>A kernel for <see cref="Ops.RmsNormBackward"/>.</summary>
    public delegate void RmsNormBackward(Backend backend, Storage dy, Storage y, Storage inv, Storage dx, int rows, int cols);

    /// <summary>A kernel for <see cref="Ops.Rope"/>.</summary>
    public delegate void Rope(Backend backend, Storage x, Storage y, Storage cos, Storage sin, Storage positions, int rows, int heads, int steps, int dim, int half, bool interleaved, float sign);

    /// <summary>A kernel for <see cref="Ops.RmsNormAffine"/>.</summary>
    public delegate void RmsNormAffine(Backend backend, Storage x, Storage gain, Storage y, int rows, int cols, float eps, float offset);

    /// <summary>A kernel for <see cref="Ops.AddRmsNormAffine"/>.</summary>
    public delegate void AddRmsNormAffine(Backend backend, Storage a, Storage b, Storage sum, Storage gain, Storage y, int rows, int cols, float eps, float offset);

    /// <summary>A kernel for <see cref="Ops.RmsNormRope"/>.</summary>
    public delegate void RmsNormRope(Backend backend, Storage x, Storage gain, Storage cos, Storage sin, Storage positions, Storage y, int rows, int cols, float eps, float offset, int heads, int steps, int half, bool interleaved);

    /// <summary>A kernel for <see cref="Ops.RmsNormRopePair"/>.</summary>
    public delegate void RmsNormRopePair(Backend backend, Storage x, Storage gain, Storage y, int rows1, float eps, float offset, int heads, Storage x2, Storage gain2, Storage y2, int rows2, float eps2, float offset2, int heads2, Storage cos, Storage sin, Storage positions, int cols, int steps, int half, bool interleaved);

    /// <summary>A kernel for <see cref="Ops.NormRopeHeads"/>.</summary>
    public delegate bool NormRopeHeads(Backend backend, Storage q, Storage k, Storage v, int batch, int steps, int heads, int kvHeads, int cols, Storage? gainQ, float epsQ, float offsetQ, Storage? gainK, float epsK, float offsetK, Storage? cos, Storage? sin, Storage? positions, int half, bool interleaved, Storage yq, Storage yk, Storage yv, Storage? position, int capacity, int stride, bool bfloat16);

    /// <summary>A kernel for <see cref="Ops.SoftmaxCrossEntropyRows"/>.</summary>
    public delegate void SoftmaxCrossEntropyRows(Backend backend, Storage logits, Storage targets, Storage weights, Storage losses, int rows, int vocabulary, float scale);

    /// <summary>A kernel for <see cref="Ops.GatedActivation"/>.</summary>
    public delegate void GatedActivation(Backend backend, Storage gate, Storage up, Storage y, int n, int kind);

    /// <summary>A kernel for <see cref="Ops.GatedActivationBackward"/>.</summary>
    public delegate void GatedActivationBackward(Backend backend, Storage gate, Storage up, Storage dy, Storage dgate, Storage dup, int n, int kind, int flags);

    /// <summary>A kernel for <see cref="Ops.GatedActivationPacked"/>.</summary>
    public delegate void GatedActivationPacked(Backend backend, Storage gate, Storage up, Storage packedGate, Storage packedUp, Storage y, Storage packedY, int n, int kind, int flags);

    /// <summary>A kernel for <see cref="Ops.GatedActivationBackwardPacked"/>.</summary>
    public delegate void GatedActivationBackwardPacked(Backend backend, Storage packedGate, Storage packedUp, Storage dy, Storage dgate, Storage dup, int n, int kind, int flags);

    /// <summary>A kernel for <see cref="Ops.KeyValueWriteInt8"/>.</summary>
    public delegate void KeyValueWriteInt8(Backend backend, Storage source, Storage cache, Storage scales, Storage position, int heads, int steps, int capacity, int dim);

    /// <summary>A kernel for <see cref="Ops.AttentionScoresInt8"/>.</summary>
    public delegate void AttentionScoresInt8(Backend backend, Storage q, Storage cache, Storage scales, Storage y, int rows, int steps, int capacity, int dim);

    /// <summary>A kernel for <see cref="Ops.AttentionContextInt8"/>.</summary>
    public delegate void AttentionContextInt8(Backend backend, Storage weights, Storage cache, Storage scales, Storage y, int rows, int steps, int capacity, int dim);

    /// <summary>A kernel for <see cref="Ops.AttentionDecode"/>.</summary>
    public delegate void AttentionDecode(Backend backend, Storage q, Storage keys, Storage values, Storage position, Storage y, int heads, int rowsPerHead, int steps, int capacity, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionInt8"/>.</summary>
    public delegate void AttentionInt8(Backend backend, Storage q, Storage keys, Storage values, Storage keyScales, Storage valueScales, Storage position, Storage y, int heads, int rowsPerHead, int steps, int capacity, int dim, float scale, bool tiled, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionBFloat16"/>.</summary>
    public delegate void AttentionBFloat16(Backend backend, Storage q, Storage keys, Storage values, Storage position, Storage y, int heads, int rowsPerHead, int steps, int capacity, int dim, float scale, bool tiled, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.KeyValueWriteBFloat16"/>.</summary>
    public delegate void KeyValueWriteBFloat16(Backend backend, Storage source, Storage cache, Storage position, int heads, int steps, int capacity, int dim);

    /// <summary>A kernel for <see cref="Ops.AttentionTiledBackward"/>.</summary>
    public delegate void AttentionTiledBackward(Backend backend, Storage q, Storage keys, Storage values, Storage output, Storage logSumExp, Storage dOutput, Storage dq, Storage dkeys, Storage dvalues, int heads, int rowsPerHead, int steps, int capacity, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionSegmented"/>.</summary>
    public delegate bool AttentionSegmented(Backend backend, Storage q, Storage keys, Storage values, Storage y, Storage? logSumExp, Storage starts, Storage ends, int heads, int headsPerRow, int rowsPerHead, int steps, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionRows"/>.</summary>
    public delegate bool AttentionRows(Backend backend, Storage q, Storage keys, Storage values, Storage position, Storage y, Storage starts, int heads, int headsPerRow, int rowsPerHead, int steps, int capacity, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionSegmentedBackward"/>.</summary>
    public delegate bool AttentionSegmentedBackward(Backend backend, Storage q, Storage keys, Storage values, Storage output, Storage logSumExp, Storage dOutput, Storage dq, Storage dkeys, Storage dvalues, Storage starts, Storage ends, int heads, int headsPerRow, int rowsPerHead, int steps, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.AttentionTiled"/>.</summary>
    public delegate void AttentionTiled(Backend backend, Storage q, Storage keys, Storage values, Storage position, Storage y, Storage? logSumExp, int heads, int rowsPerHead, int steps, int capacity, int dim, float scale, AttentionVariant variant);

    /// <summary>A kernel for <see cref="Ops.DecoderMask"/>.</summary>
    public delegate void DecoderMask(Backend backend, Storage position, Storage mask, int rows, int capacity);

    /// <summary>A kernel for <see cref="Ops.KeyValueWrite"/>.</summary>
    public delegate void KeyValueWrite(Backend backend, Storage source, Storage cache, Storage position, int heads, int steps, int capacity, int dim);

    /// <summary>A kernel for <see cref="Ops.SampleRows"/>.</summary>
    public delegate void SampleRows(Backend backend, Storage logits, Storage ids, Storage stats, Storage step, int rows, int vocabulary, int rowStride, int rowOffset, float temperature, int topK, float topP, float minP, uint seed);

    /// <summary>A kernel for <see cref="Ops.PenalizeRows"/>.</summary>
    public delegate void PenalizeRows(Backend backend, Storage logits, Storage work, Storage history, Storage length, int rows, int vocabulary, int rowStride, int rowOffset, int capacity, int lastN, float repeat, float presence, float frequency);

    /// <summary>A kernel for <see cref="Ops.HistoryPush"/>.</summary>
    public delegate void HistoryPush(Backend backend, Storage ids, Storage history, Storage length, int rows, int capacity);
}

internal static partial class Ops
{
    /// <summary>The operation Fill.</summary>
    public static readonly Operation Fill = new("Fill", OperationIndex.Fill, typeof(OperationKernels.Fill));

    /// <summary>The operation Unary.</summary>
    public static readonly Operation Unary = new("Unary", OperationIndex.Unary, typeof(OperationKernels.Unary));

    /// <summary>The operation UnaryBackward.</summary>
    public static readonly Operation UnaryBackward = new("UnaryBackward", OperationIndex.UnaryBackward, typeof(OperationKernels.UnaryBackward));

    /// <summary>The operation Binary.</summary>
    public static readonly Operation Binary = new("Binary", OperationIndex.Binary, typeof(OperationKernels.Binary));

    /// <summary>The operation ExtremumBackward.</summary>
    public static readonly Operation ExtremumBackward = new("ExtremumBackward", OperationIndex.ExtremumBackward, typeof(OperationKernels.ExtremumBackward));

    /// <summary>The operation Pow.</summary>
    public static readonly Operation Pow = new("Pow", OperationIndex.Pow, typeof(OperationKernels.Pow));

    /// <summary>The operation PowBackward.</summary>
    public static readonly Operation PowBackward = new("PowBackward", OperationIndex.PowBackward, typeof(OperationKernels.PowBackward));

    /// <summary>The operation Clamp.</summary>
    public static readonly Operation Clamp = new("Clamp", OperationIndex.Clamp, typeof(OperationKernels.Clamp));

    /// <summary>The operation ClampBackward.</summary>
    public static readonly Operation ClampBackward = new("ClampBackward", OperationIndex.ClampBackward, typeof(OperationKernels.ClampBackward));

    /// <summary>The operation Where.</summary>
    public static readonly Operation Where = new("Where", OperationIndex.Where, typeof(OperationKernels.Where));

    /// <summary>The operation WhereBackward.</summary>
    public static readonly Operation WhereBackward = new("WhereBackward", OperationIndex.WhereBackward, typeof(OperationKernels.WhereBackward));

    /// <summary>The operation Affine.</summary>
    public static readonly Operation Affine = new("Affine", OperationIndex.Affine, typeof(OperationKernels.Affine));

    /// <summary>The operation Axpy.</summary>
    public static readonly Operation Axpy = new("Axpy", OperationIndex.Axpy, typeof(OperationKernels.Axpy));

    /// <summary>The operation MulAdd.</summary>
    public static readonly Operation MulAdd = new("MulAdd", OperationIndex.MulAdd, typeof(OperationKernels.MulAdd));

    /// <summary>The operation AddRowVector.</summary>
    public static readonly Operation AddRowVector = new("AddRowVector", OperationIndex.AddRowVector, typeof(OperationKernels.AddRowVector));

    /// <summary>The operation SumRows.</summary>
    public static readonly Operation SumRows = new("SumRows", OperationIndex.SumRows, typeof(OperationKernels.SumRows));

    /// <summary>The operation Sum.</summary>
    public static readonly Operation Sum = new("Sum", OperationIndex.Sum, typeof(OperationKernels.Sum));

    /// <summary>The operation AxpyAt.</summary>
    public static readonly Operation AxpyAt = new("AxpyAt", OperationIndex.AxpyAt, typeof(OperationKernels.AxpyAt));

    /// <summary>The operation AddBroadcastScalar.</summary>
    public static readonly Operation AddBroadcastScalar = new("AddBroadcastScalar", OperationIndex.AddBroadcastScalar, typeof(OperationKernels.AddBroadcastScalar));

    /// <summary>The operation PackedMatMulLarge.</summary>
    public static readonly Operation PackedMatMulLarge = new("PackedMatMulLarge", OperationIndex.PackedMatMulLarge, typeof(OperationKernels.PackedMatMulLarge));

    /// <summary>The operation PackedMatMulGated.</summary>
    public static readonly Operation PackedMatMulGated = new("PackedMatMulGated", OperationIndex.PackedMatMulGated, typeof(OperationKernels.PackedMatMulGated));

    /// <summary>The operation PackedMatMulAddRmsNorm.</summary>
    public static readonly Operation PackedMatMulAddRmsNorm = new("PackedMatMulAddRmsNorm", OperationIndex.PackedMatMulAddRmsNorm, typeof(OperationKernels.PackedMatMulAddRmsNorm));

    /// <summary>The operation PackedMatMulMany.</summary>
    public static readonly Operation PackedMatMulMany = new("PackedMatMulMany", OperationIndex.PackedMatMulMany, typeof(OperationKernels.PackedMatMulMany));

    /// <summary>The operation PackedMatMulGatedPair.</summary>
    public static readonly Operation PackedMatMulGatedPair = new("PackedMatMulGatedPair", OperationIndex.PackedMatMulGatedPair, typeof(OperationKernels.PackedMatMulGatedPair));

    /// <summary>The operation MatMulMany.</summary>
    public static readonly Operation MatMulMany = new("MatMulMany", OperationIndex.MatMulMany, typeof(OperationKernels.MatMulMany));

    /// <summary>The operation MatMulBias.</summary>
    public static readonly Operation MatMulBias = new("MatMulBias", OperationIndex.MatMulBias, typeof(OperationKernels.MatMulBias));

    /// <summary>The operation MatMulLowRank.</summary>
    public static readonly Operation MatMulLowRank = new("MatMulLowRank", OperationIndex.MatMulLowRank, typeof(OperationKernels.MatMulLowRank));

    /// <summary>The operation BFloat16TransposedMatMul.</summary>
    public static readonly Operation BFloat16TransposedMatMul = new("BFloat16TransposedMatMul", OperationIndex.BFloat16TransposedMatMul, typeof(OperationKernels.BFloat16TransposedMatMul));

    /// <summary>The operation Float8QuantizeWeight.</summary>
    public static readonly Operation Float8QuantizeWeight = new("Float8QuantizeWeight", OperationIndex.Float8QuantizeWeight, typeof(OperationKernels.Float8QuantizeWeight));

    /// <summary>The operation Float8MatMul.</summary>
    public static readonly Operation Float8MatMul = new("Float8MatMul", OperationIndex.Float8MatMul, typeof(OperationKernels.Float8MatMul));

    /// <summary>The operation PackedMatMulLowRank.</summary>
    public static readonly Operation PackedMatMulLowRank = new("PackedMatMulLowRank", OperationIndex.PackedMatMulLowRank, typeof(OperationKernels.PackedMatMulLowRank));

    /// <summary>The operation GemmStrided.</summary>
    public static readonly Operation GemmStrided = new("GemmStrided", OperationIndex.GemmStrided, typeof(OperationKernels.GemmStrided));

    /// <summary>The operation AttentionStrided.</summary>
    public static readonly Operation AttentionStrided = new("AttentionStrided", OperationIndex.AttentionStrided, typeof(OperationKernels.AttentionStrided));

    /// <summary>The operation AttentionStridedBackward.</summary>
    public static readonly Operation AttentionStridedBackward = new("AttentionStridedBackward", OperationIndex.AttentionStridedBackward, typeof(OperationKernels.AttentionStridedBackward));

    /// <summary>The operation SumColumns.</summary>
    public static readonly Operation SumColumns = new("SumColumns", OperationIndex.SumColumns, typeof(OperationKernels.SumColumns));

    /// <summary>The operation AddDropout.</summary>
    public static readonly Operation AddDropout = new("AddDropout", OperationIndex.AddDropout, typeof(OperationKernels.AddDropout));

    /// <summary>The operation BatchedMatMul.</summary>
    public static readonly Operation BatchedMatMul = new("BatchedMatMul", OperationIndex.BatchedMatMul, typeof(OperationKernels.BatchedMatMul));

    /// <summary>The operation Softmax.</summary>
    public static readonly Operation Softmax = new("Softmax", OperationIndex.Softmax, typeof(OperationKernels.Softmax));

    /// <summary>The operation SoftmaxBackward.</summary>
    public static readonly Operation SoftmaxBackward = new("SoftmaxBackward", OperationIndex.SoftmaxBackward, typeof(OperationKernels.SoftmaxBackward));

    /// <summary>The operation ArgMax.</summary>
    public static readonly Operation ArgMax = new("ArgMax", OperationIndex.ArgMax, typeof(OperationKernels.ArgMax));

    /// <summary>The operation ClassMatch.</summary>
    public static readonly Operation ClassMatch = new("ClassMatch", OperationIndex.ClassMatch, typeof(OperationKernels.ClassMatch));

    /// <summary>The operation NormStats.</summary>
    public static readonly Operation NormStats = new("NormStats", OperationIndex.NormStats, typeof(OperationKernels.NormStats));

    /// <summary>The operation NormApply.</summary>
    public static readonly Operation NormApply = new("NormApply", OperationIndex.NormApply, typeof(OperationKernels.NormApply));

    /// <summary>The operation NormBackward.</summary>
    public static readonly Operation NormBackward = new("NormBackward", OperationIndex.NormBackward, typeof(OperationKernels.NormBackward));

    /// <summary>The operation GroupScaleShift.</summary>
    public static readonly Operation GroupScaleShift = new("GroupScaleShift", OperationIndex.GroupScaleShift, typeof(OperationKernels.GroupScaleShift));

    /// <summary>The operation GroupReduce.</summary>
    public static readonly Operation GroupReduce = new("GroupReduce", OperationIndex.GroupReduce, typeof(OperationKernels.GroupReduce));

    /// <summary>The operation InvSqrt.</summary>
    public static readonly Operation InvSqrt = new("InvSqrt", OperationIndex.InvSqrt, typeof(OperationKernels.InvSqrt));

    /// <summary>The operation Gather.</summary>
    public static readonly Operation Gather = new("Gather", OperationIndex.Gather, typeof(OperationKernels.Gather));

    /// <summary>The operation GatherBFloat16.</summary>
    public static readonly Operation GatherBFloat16 = new("GatherBFloat16", OperationIndex.GatherBFloat16, typeof(OperationKernels.GatherBFloat16));

    /// <summary>The operation OneHot.</summary>
    public static readonly Operation OneHot = new("OneHot", OperationIndex.OneHot, typeof(OperationKernels.OneHot));

    /// <summary>The operation ScatterAdd.</summary>
    public static readonly Operation ScatterAdd = new("ScatterAdd", OperationIndex.ScatterAdd, typeof(OperationKernels.ScatterAdd));

    /// <summary>The operation Im2Col.</summary>
    public static readonly Operation Im2Col = new("Im2Col", OperationIndex.Im2Col, typeof(OperationKernels.Im2Col));

    /// <summary>The operation Col2Im.</summary>
    public static readonly Operation Col2Im = new("Col2Im", OperationIndex.Col2Im, typeof(OperationKernels.Col2Im));

    /// <summary>The operation MaxPool.</summary>
    public static readonly Operation MaxPool = new("MaxPool", OperationIndex.MaxPool, typeof(OperationKernels.MaxPool));

    /// <summary>The operation MaxPoolBackward.</summary>
    public static readonly Operation MaxPoolBackward = new("MaxPoolBackward", OperationIndex.MaxPoolBackward, typeof(OperationKernels.MaxPoolBackward));

    /// <summary>The operation MaxPoolBackward2.</summary>
    public static readonly Operation MaxPoolBackward2 = new("MaxPoolBackward2", OperationIndex.MaxPoolBackward2, typeof(OperationKernels.MaxPoolBackward2));

    /// <summary>The operation Permute.</summary>
    public static readonly Operation Permute = new("Permute", OperationIndex.Permute, typeof(OperationKernels.Permute));

    /// <summary>The operation SumAxis.</summary>
    public static readonly Operation SumAxis = new("SumAxis", OperationIndex.SumAxis, typeof(OperationKernels.SumAxis));

    /// <summary>The operation BroadcastAxis.</summary>
    public static readonly Operation BroadcastAxis = new("BroadcastAxis", OperationIndex.BroadcastAxis, typeof(OperationKernels.BroadcastAxis));

    /// <summary>The operation SgdStep.</summary>
    public static readonly Operation SgdStep = new("SgdStep", OperationIndex.SgdStep, typeof(OperationKernels.SgdStep));

    /// <summary>The operation AdamStep.</summary>
    public static readonly Operation AdamStep = new("AdamStep", OperationIndex.AdamStep, typeof(OperationKernels.AdamStep));

    /// <summary>The operation AdamStep8Bit.</summary>
    public static readonly Operation AdamStep8Bit = new("AdamStep8Bit", OperationIndex.AdamStep8Bit, typeof(OperationKernels.AdamStep8Bit));

    /// <summary>The operation SumSquares.</summary>
    public static readonly Operation SumSquares = new("SumSquares", OperationIndex.SumSquares, typeof(OperationKernels.SumSquares));

    /// <summary>The operation FusedAdamW.</summary>
    public static readonly Operation FusedAdamW = new("FusedAdamW", OperationIndex.FusedAdamW, typeof(OperationKernels.FusedAdamW));

    /// <summary>The operation ClipFactor.</summary>
    public static readonly Operation ClipFactor = new("ClipFactor", OperationIndex.ClipFactor, typeof(OperationKernels.ClipFactor));

    /// <summary>The operation Dropout.</summary>
    public static readonly Operation Dropout = new("Dropout", OperationIndex.Dropout, typeof(OperationKernels.Dropout));

    /// <summary>The operation DropoutBackward.</summary>
    public static readonly Operation DropoutBackward = new("DropoutBackward", OperationIndex.DropoutBackward, typeof(OperationKernels.DropoutBackward));

    /// <summary>The operation ScaleMaskSoftmax.</summary>
    public static readonly Operation ScaleMaskSoftmax = new("ScaleMaskSoftmax", OperationIndex.ScaleMaskSoftmax, typeof(OperationKernels.ScaleMaskSoftmax));

    /// <summary>The operation LayerNormFused.</summary>
    public static readonly Operation LayerNormFused = new("LayerNormFused", OperationIndex.LayerNormFused, typeof(OperationKernels.LayerNormFused));

    /// <summary>The operation LayerNormTrain.</summary>
    public static readonly Operation LayerNormTrain = new("LayerNormTrain", OperationIndex.LayerNormTrain, typeof(OperationKernels.LayerNormTrain));

    /// <summary>The operation LayerNormBackward.</summary>
    public static readonly Operation LayerNormBackward = new("LayerNormBackward", OperationIndex.LayerNormBackward, typeof(OperationKernels.LayerNormBackward));

    /// <summary>The operation BiasGelu.</summary>
    public static readonly Operation BiasGelu = new("BiasGelu", OperationIndex.BiasGelu, typeof(OperationKernels.BiasGelu));

    /// <summary>The operation Int8MatMul.</summary>
    public static readonly Operation Int8MatMul = new("Int8MatMul", OperationIndex.Int8MatMul, typeof(OperationKernels.Int8MatMul));

    /// <summary>The operation BFloat16MatMul.</summary>
    public static readonly Operation BFloat16MatMul = new("BFloat16MatMul", OperationIndex.BFloat16MatMul, typeof(OperationKernels.BFloat16MatMul));

    /// <summary>The operation BFloat16Dequantize.</summary>
    public static readonly Operation BFloat16Dequantize = new("BFloat16Dequantize", OperationIndex.BFloat16Dequantize, typeof(OperationKernels.BFloat16Dequantize));

    /// <summary>The operation PackBFloat16.</summary>
    public static readonly Operation PackBFloat16 = new("PackBFloat16", OperationIndex.PackBFloat16, typeof(OperationKernels.PackBFloat16));

    /// <summary>The operation Int8Dequantize.</summary>
    public static readonly Operation Int8Dequantize = new("Int8Dequantize", OperationIndex.Int8Dequantize, typeof(OperationKernels.Int8Dequantize));

    /// <summary>The operation Int4MatMul.</summary>
    public static readonly Operation Int4MatMul = new("Int4MatMul", OperationIndex.Int4MatMul, typeof(OperationKernels.Int4MatMul));

    /// <summary>The operation Int4Dequantize.</summary>
    public static readonly Operation Int4Dequantize = new("Int4Dequantize", OperationIndex.Int4Dequantize, typeof(OperationKernels.Int4Dequantize));

    /// <summary>The operation RmsNorm.</summary>
    public static readonly Operation RmsNorm = new("RmsNorm", OperationIndex.RmsNorm, typeof(OperationKernels.RmsNorm));

    /// <summary>The operation RmsNormBackward.</summary>
    public static readonly Operation RmsNormBackward = new("RmsNormBackward", OperationIndex.RmsNormBackward, typeof(OperationKernels.RmsNormBackward));

    /// <summary>The operation Rope.</summary>
    public static readonly Operation Rope = new("Rope", OperationIndex.Rope, typeof(OperationKernels.Rope));

    /// <summary>The operation RmsNormAffine.</summary>
    public static readonly Operation RmsNormAffine = new("RmsNormAffine", OperationIndex.RmsNormAffine, typeof(OperationKernels.RmsNormAffine));

    /// <summary>The operation AddRmsNormAffine.</summary>
    public static readonly Operation AddRmsNormAffine = new("AddRmsNormAffine", OperationIndex.AddRmsNormAffine, typeof(OperationKernels.AddRmsNormAffine));

    /// <summary>The operation RmsNormRope.</summary>
    public static readonly Operation RmsNormRope = new("RmsNormRope", OperationIndex.RmsNormRope, typeof(OperationKernels.RmsNormRope));

    /// <summary>The operation RmsNormRopePair.</summary>
    public static readonly Operation RmsNormRopePair = new("RmsNormRopePair", OperationIndex.RmsNormRopePair, typeof(OperationKernels.RmsNormRopePair));

    /// <summary>The operation NormRopeHeads.</summary>
    public static readonly Operation NormRopeHeads = new("NormRopeHeads", OperationIndex.NormRopeHeads, typeof(OperationKernels.NormRopeHeads));

    /// <summary>The operation SoftmaxCrossEntropyRows.</summary>
    public static readonly Operation SoftmaxCrossEntropyRows = new("SoftmaxCrossEntropyRows", OperationIndex.SoftmaxCrossEntropyRows, typeof(OperationKernels.SoftmaxCrossEntropyRows));

    /// <summary>The operation GatedActivation.</summary>
    public static readonly Operation GatedActivation = new("GatedActivation", OperationIndex.GatedActivation, typeof(OperationKernels.GatedActivation));

    /// <summary>The operation GatedActivationBackward.</summary>
    public static readonly Operation GatedActivationBackward = new("GatedActivationBackward", OperationIndex.GatedActivationBackward, typeof(OperationKernels.GatedActivationBackward));

    /// <summary>The operation GatedActivationPacked.</summary>
    public static readonly Operation GatedActivationPacked = new("GatedActivationPacked", OperationIndex.GatedActivationPacked, typeof(OperationKernels.GatedActivationPacked));

    /// <summary>The operation GatedActivationBackwardPacked.</summary>
    public static readonly Operation GatedActivationBackwardPacked = new("GatedActivationBackwardPacked", OperationIndex.GatedActivationBackwardPacked, typeof(OperationKernels.GatedActivationBackwardPacked));

    /// <summary>The operation KeyValueWriteInt8.</summary>
    public static readonly Operation KeyValueWriteInt8 = new("KeyValueWriteInt8", OperationIndex.KeyValueWriteInt8, typeof(OperationKernels.KeyValueWriteInt8));

    /// <summary>The operation AttentionScoresInt8.</summary>
    public static readonly Operation AttentionScoresInt8 = new("AttentionScoresInt8", OperationIndex.AttentionScoresInt8, typeof(OperationKernels.AttentionScoresInt8));

    /// <summary>The operation AttentionContextInt8.</summary>
    public static readonly Operation AttentionContextInt8 = new("AttentionContextInt8", OperationIndex.AttentionContextInt8, typeof(OperationKernels.AttentionContextInt8));

    /// <summary>The operation AttentionDecode.</summary>
    public static readonly Operation AttentionDecode = new("AttentionDecode", OperationIndex.AttentionDecode, typeof(OperationKernels.AttentionDecode));

    /// <summary>The operation AttentionInt8.</summary>
    public static readonly Operation AttentionInt8 = new("AttentionInt8", OperationIndex.AttentionInt8, typeof(OperationKernels.AttentionInt8));

    /// <summary>The operation AttentionBFloat16.</summary>
    public static readonly Operation AttentionBFloat16 = new("AttentionBFloat16", OperationIndex.AttentionBFloat16, typeof(OperationKernels.AttentionBFloat16));

    /// <summary>The operation KeyValueWriteBFloat16.</summary>
    public static readonly Operation KeyValueWriteBFloat16 = new("KeyValueWriteBFloat16", OperationIndex.KeyValueWriteBFloat16, typeof(OperationKernels.KeyValueWriteBFloat16));

    /// <summary>The operation AttentionTiledBackward.</summary>
    public static readonly Operation AttentionTiledBackward = new("AttentionTiledBackward", OperationIndex.AttentionTiledBackward, typeof(OperationKernels.AttentionTiledBackward));

    /// <summary>The operation AttentionSegmented.</summary>
    public static readonly Operation AttentionSegmented = new("AttentionSegmented", OperationIndex.AttentionSegmented, typeof(OperationKernels.AttentionSegmented));

    /// <summary>The operation AttentionRows.</summary>
    public static readonly Operation AttentionRows = new("AttentionRows", OperationIndex.AttentionRows, typeof(OperationKernels.AttentionRows));

    /// <summary>The operation AttentionSegmentedBackward.</summary>
    public static readonly Operation AttentionSegmentedBackward = new("AttentionSegmentedBackward", OperationIndex.AttentionSegmentedBackward, typeof(OperationKernels.AttentionSegmentedBackward));

    /// <summary>The operation AttentionTiled.</summary>
    public static readonly Operation AttentionTiled = new("AttentionTiled", OperationIndex.AttentionTiled, typeof(OperationKernels.AttentionTiled));

    /// <summary>The operation DecoderMask.</summary>
    public static readonly Operation DecoderMask = new("DecoderMask", OperationIndex.DecoderMask, typeof(OperationKernels.DecoderMask));

    /// <summary>The operation KeyValueWrite.</summary>
    public static readonly Operation KeyValueWrite = new("KeyValueWrite", OperationIndex.KeyValueWrite, typeof(OperationKernels.KeyValueWrite));

    /// <summary>The operation SampleRows.</summary>
    public static readonly Operation SampleRows = new("SampleRows", OperationIndex.SampleRows, typeof(OperationKernels.SampleRows));

    /// <summary>The operation PenalizeRows.</summary>
    public static readonly Operation PenalizeRows = new("PenalizeRows", OperationIndex.PenalizeRows, typeof(OperationKernels.PenalizeRows));

    /// <summary>The operation HistoryPush.</summary>
    public static readonly Operation HistoryPush = new("HistoryPush", OperationIndex.HistoryPush, typeof(OperationKernels.HistoryPush));

    /// <summary>Every operation, by index.</summary>
    public static IReadOnlyList<Operation> All { get; } =
    [
        Fill,
        Unary,
        UnaryBackward,
        Binary,
        ExtremumBackward,
        Pow,
        PowBackward,
        Clamp,
        ClampBackward,
        Where,
        WhereBackward,
        Affine,
        Axpy,
        MulAdd,
        AddRowVector,
        SumRows,
        Sum,
        AxpyAt,
        AddBroadcastScalar,
        PackedMatMulLarge,
        PackedMatMulGated,
        PackedMatMulAddRmsNorm,
        PackedMatMulMany,
        PackedMatMulGatedPair,
        MatMulMany,
        MatMulBias,
        MatMulLowRank,
        BFloat16TransposedMatMul,
        Float8QuantizeWeight,
        Float8MatMul,
        PackedMatMulLowRank,
        GemmStrided,
        AttentionStrided,
        AttentionStridedBackward,
        SumColumns,
        AddDropout,
        BatchedMatMul,
        Softmax,
        SoftmaxBackward,
        ArgMax,
        ClassMatch,
        NormStats,
        NormApply,
        NormBackward,
        GroupScaleShift,
        GroupReduce,
        InvSqrt,
        Gather,
        GatherBFloat16,
        OneHot,
        ScatterAdd,
        Im2Col,
        Col2Im,
        MaxPool,
        MaxPoolBackward,
        MaxPoolBackward2,
        Permute,
        SumAxis,
        BroadcastAxis,
        SgdStep,
        AdamStep,
        AdamStep8Bit,
        SumSquares,
        FusedAdamW,
        ClipFactor,
        Dropout,
        DropoutBackward,
        ScaleMaskSoftmax,
        LayerNormFused,
        LayerNormTrain,
        LayerNormBackward,
        BiasGelu,
        Int8MatMul,
        BFloat16MatMul,
        BFloat16Dequantize,
        PackBFloat16,
        Int8Dequantize,
        Int4MatMul,
        Int4Dequantize,
        RmsNorm,
        RmsNormBackward,
        Rope,
        RmsNormAffine,
        AddRmsNormAffine,
        RmsNormRope,
        RmsNormRopePair,
        NormRopeHeads,
        SoftmaxCrossEntropyRows,
        GatedActivation,
        GatedActivationBackward,
        GatedActivationPacked,
        GatedActivationBackwardPacked,
        KeyValueWriteInt8,
        AttentionScoresInt8,
        AttentionContextInt8,
        AttentionDecode,
        AttentionInt8,
        AttentionBFloat16,
        KeyValueWriteBFloat16,
        AttentionTiledBackward,
        AttentionSegmented,
        AttentionRows,
        AttentionSegmentedBackward,
        AttentionTiled,
        DecoderMask,
        KeyValueWrite,
        SampleRows,
        PenalizeRows,
        HistoryPush,
    ];
}
