"""Generates the operation table (plan 9) from the device contract.

Every operation of the device contract is a virtual method `NameKernel` on `Backend`
(src/Idrak.Abstraction/Devices/Backend.cs): the device's own kernel, whose default body is the host fallback, a
composition of other operations, or none (it returns false). From those declarations and their documentation this
script writes

  src/Idrak.Abstraction/Operations/Operations.g.cs    a descriptor per operation (Ops), its index and its kernel
                                                      delegate (OperationKernels), with what its default body does
  src/Idrak.Abstraction/Devices/Backend.Operations.g.cs
                                                      `Name(...)` on Backend, which runs the kernel registered for the
                                                      device (Kernels.Register) or else `NameKernel`
  src/Idrak.Abstraction.Testing/Devices/OperationCalls.g.cs
                                                      the testing kit's recorder (a kernel per operation that reports
                                                      each call with its arguments) and replay (`Name(...)` from the
                                                      recorded arguments), for the device conformance check

Every `NameKernel` needs a `<summary>`: the descriptor, the delegate and `Name(...)` reuse it.

Run it after adding, removing or changing an operation:

  python3 tools/operations/generate.py

The test "operations: ..." in tests/Idrak.Tests/OperationTests.cs fails when the generated files and Backend disagree.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BACKEND = ROOT / "src/Idrak.Abstraction/Devices/Backend.cs"
OPERATIONS = ROOT / "src/Idrak.Abstraction/Operations/Operations.g.cs"
DISPATCH = ROOT / "src/Idrak.Abstraction/Devices/Backend.Operations.g.cs"
CALLS = ROOT / "src/Idrak.Abstraction.Testing/Devices/OperationCalls.g.cs"

HEADER = """// <auto-generated>
// Generated by tools/operations/generate.py from src/Idrak.Abstraction/Devices/Backend.cs; do not edit.
// </auto-generated>
// Copyright (c) 2026 Ahmed Seada
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

#nullable enable
"""


def split_top(text, sep=","):
    """Splits on `sep` outside brackets, parentheses and generic arguments."""
    parts, depth, current = [], 0, ""
    for ch in text:
        if ch in "([<{":
            depth += 1
        elif ch in ")]>}":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        parts.append(current)
    return [p.strip() for p in parts]


def strip_default(parameter):
    """The parameter without its default value."""
    depth = 0
    for i, ch in enumerate(parameter):
        if ch in "([<{":
            depth += 1
        elif ch in ")]>}":
            depth -= 1
        elif ch == "=" and depth == 0:
            return parameter[:i].strip()
    return parameter


def argument(parameter):
    """The argument passing a parameter on: its name, with ref, out or in."""
    words = strip_default(parameter).split()
    modifier = next((w for w in words if w in ("ref", "out", "in")), None)
    name = words[-1]
    return f"{modifier} {name}" if modifier else name


PRIMITIVES = {"int": "Int32", "float": "Single", "uint": "UInt32", "long": "Int64", "bool": "Boolean", "double": "Double",
              "byte": "Byte", "nint": "IntPtr"}


def clr_name(parameter):
    """The .NET Type.Name of a parameter's type (Int32, Storage, ConvGeometry&, ReadOnlySpan`1), to find its method."""
    words = strip_default(parameter).split()
    byref = any(w in ("ref", "out", "in") for w in words[:-1])
    declared = " ".join(w for w in words[:-1] if w not in ("ref", "out", "in", "params", "scoped")).rstrip("?")
    if "<" in declared:
        arguments = split_top(declared[declared.index("<") + 1:-1])
        name = f"{declared[:declared.index('<')]}`{len(arguments)}"
    else:
        name = PRIMITIVES.get(declared, declared)
    return name + ("&" if byref else "")


def parts(parameter):
    """(modifier, type, name) of a parameter: modifier is ref, out, in or None."""
    words = strip_default(parameter).split()
    modifier = next((w for w in words[:-1] if w in ("ref", "out", "in")), None)
    declared = " ".join(w for w in words[:-1] if w not in ("ref", "out", "in", "params", "scoped"))
    return modifier, declared, words[-1]


def tuple_types(declared):
    """The element types of a span of tuples, `ReadOnlySpan<(Storage Packed, int Columns)>` -> [Storage, int]."""
    inner = declared[declared.index("(") + 1:declared.rindex(")")]
    return [" ".join(element.split()[:-1]) for element in split_top(inner)]


def recorded(parameter):
    """How the recorder keeps an argument: storages and values as they are, spans as arrays, a ref cache as null."""
    modifier, declared, name = parts(parameter)
    if modifier == "ref":
        return "null"
    if declared.startswith("ReadOnlySpan<("):
        items = ", ".join(f"t.Item{i + 1}" for i in range(len(tuple_types(declared))))
        return f"Array.ConvertAll({name}.ToArray(), t => new object?[] {{ {items} }})"
    if declared.startswith("ReadOnlySpan<"):
        return f"{name}.ToArray()"
    return name


def unboxed(declared, value):
    """A recorded value cast back to its declared type."""
    return f"({declared}){value}" if declared.endswith("?") else f"({declared}){value}!"


def replayed(parameter, i):
    """The argument a replay passes from the recorded `a[i]`."""
    modifier, declared, _name = parts(parameter)
    if modifier == "ref":
        return "ref cache"
    if declared.startswith("ReadOnlySpan<("):
        items = ", ".join(unboxed(t, f"t[{j}]") for j, t in enumerate(tuple_types(declared)))
        return f"Array.ConvertAll((object?[][])a[{i}]!, t => ({items}))"
    if declared.startswith("ReadOnlySpan<"):
        element = declared[declared.index("<") + 1:-1]
        return f"({element}[])a[{i}]!"
    return unboxed(declared, f"a[{i}]")


def documentation(source, start):
    """The `///` lines right above the declaration starting at `start`, without their indentation and slashes."""
    lines = source[:start].split("\n")[:-1]
    block = []
    while lines and lines[-1].strip().startswith("///"):
        block.insert(0, lines.pop().strip()[3:].removeprefix(" "))
    return block


def body(source, end):
    """The default body after the parameter list at `end`: `=> ...;` or a block, as written."""
    rest = source[end:].lstrip()
    if rest.startswith("=>"):
        return rest[:rest.index(";") + 1]
    depth, i = 0, 0
    while True:
        depth += {"{": 1, "}": -1}.get(rest[i], 0)
        i += 1
        if depth == 0 and rest[i - 1] == "}":
            break
    return rest[:i]


def fallback(source, end):
    """What the default body after the parameter list at `end` does: KernelSource.None, Host or Composed."""
    text = body(source, end)
    if text.startswith("=>"):
        return "None" if re.fullmatch(r"=>\s*(false|0)\s*;", text) else "Composed"
    return "Host" if "new HostCall(" in text else "Composed"


def operations(source):
    """(name, return type, parameter list, doc lines, fallback, body) of every `public virtual ... NameKernel(...)` in order."""
    found = []
    for match in re.finditer(r"^    public virtual (.+?) (\w+)Kernel\(", source, re.M):
        start = match.end()
        depth, i = 1, start
        while depth:
            depth += {"(": 1, ")": -1}.get(source[i], 0)
            i += 1
        parameters = " ".join(source[start:i - 1].split())
        docs = documentation(source, match.start())
        if not any(line.startswith("<summary>") for line in docs):
            sys.exit(f"{match.group(2)}Kernel in {BACKEND} has no <summary>: the generated descriptor needs one")
        found.append((match.group(2), match.group(1), parameters, docs, fallback(source, i), body(source, i)))
    return found


def summary(docs):
    """The text of the `<summary>` element of a doc block, as lines."""
    text = "\n".join(docs)
    inner = text[text.index("<summary>") + len("<summary>"):text.index("</summary>")]
    return [line for line in inner.strip("\n").split("\n")]


def outside_backend(lines, members):
    """Doc lines for a declaration outside Backend: crefs to Backend's members qualified, parameter references as code."""
    result = []
    for line in lines:
        line = re.sub(r'<see cref="(\w+)"\s*/>', lambda m: f'<see cref="Backend.{m.group(1)}"/>' if m.group(1) in members else m.group(0), line)
        result.append(line)
    return result


def as_code(lines):
    """Parameter references written as code (for a declaration without those parameters)."""
    return [re.sub(r'<paramref name="(\w+)"\s*/>', r"<c>\1</c>", line) for line in lines]


def generate():
    source = BACKEND.read_text(encoding="utf-8")
    ops = operations(source)
    if not ops:
        sys.exit(f"no `public virtual ... NameKernel(` in {BACKEND}")
    members = set(re.findall(r"^    public (?:abstract |virtual |override |static )*[\w<>?,\[\]() ]+? (\w+)[(\s]", source, re.M))
    members |= {name for name, *_ in ops}

    # Overloads share the method name; their descriptors and delegates are numbered (MaxPoolBackward, MaxPoolBackward2).
    seen, named, bodies = {}, [], {}
    for name, returns, parameters, docs, default, text in ops:
        seen[name] = seen.get(name, 0) + 1
        op = name if seen[name] == 1 else f"{name}{seen[name]}"
        named.append((name, op, returns, parameters, docs, default))
        bodies[op] = text

    o = [HEADER, "using Idrak.Abstraction.Devices;", "", "namespace Idrak.Abstraction.Operations;", ""]
    o.append("/// <summary>The index of each operation in a device's kernel slots (see <see cref=\"Ops\"/>).</summary>")
    o.append("internal static class OperationIndex")
    o.append("{")
    for index, (_, op, *_rest) in enumerate(named):
        o.append(f"    public const int {op} = {index};")
    o.append("")
    o.append(f"    /// <summary>The number of operations.</summary>")
    o.append(f"    public const int Count = {len(named)};")
    o.append("}")
    o.append("")
    o.append("/// <summary>")
    o.append("/// The kernel delegate of each operation (<see cref=\"Operation.KernelType\"/>): the device's backend, then the operation's")
    o.append("/// arguments. A kernel registered with <see cref=\"Kernels.Register\"/> has its operation's type.")
    o.append("/// </summary>")
    o.append("public static class OperationKernels")
    o.append("{")
    for i, (_, op, returns, parameters, docs, _default) in enumerate(named):
        plain = ", ".join(strip_default(p) for p in split_top(parameters))
        if i:
            o.append("")
        o.append("    /// <summary>")
        o.append(f"    /// A kernel for <see cref=\"Ops.{op}\"/>, given the device it runs on (<c>backend</c>) and the operation's arguments:")
        o.extend(f"    /// {line}".rstrip() for line in outside_backend(summary(docs), members))
        o.append("    /// </summary>")
        o.append(f"    public delegate {returns} {op}(Backend backend{', ' + plain if plain else ''});")
    o.append("}")
    o.append("")
    o.append("/// <summary>")
    o.append("/// The operations of the device contract (plan 9), one descriptor each, in slot order. A device runs each through")
    o.append("/// <c>Backend.Name(...)</c>; <see cref=\"Kernels.Register\"/> adds kernels for them.")
    o.append("/// </summary>")
    o.append("public static partial class Ops")
    o.append("{")
    for method, op, _returns, _parameters, docs, default in named:
        o.append("    /// <summary>")
        o.extend(f"    /// {line}".rstrip() for line in as_code(outside_backend(summary(docs), members)))
        o.append("    /// </summary>")
        signature = ",".join(clr_name(p) for p in split_top(_parameters))
        o.append(f"    public static readonly Operation {op} =")
        o.append(f"        new(\"{op}\", \"{method}Kernel\", \"{signature}\", OperationIndex.{op}, typeof(OperationKernels.{op}), KernelSource.{default});")
        o.append("")
    o.append("    /// <summary>Every operation, by <see cref=\"Operation.Index\"/>.</summary>")
    o.append("    public static IReadOnlyList<Operation> All { get; } =")
    o.append("    [")
    for _, op, *_rest in named:
        o.append(f"        {op},")
    o.append("    ];")
    o.append("")
    o.append("    /// <summary>The operation named <paramref name=\"name\"/> (as <see cref=\"Operation.Name\"/>, any case), or null.</summary>")
    o.append("    public static Operation? Find(string name)")
    o.append("    {")
    o.append("        foreach (var operation in All)")
    o.append("        {")
    o.append("            if (operation.Name.Equals(name, StringComparison.OrdinalIgnoreCase))")
    o.append("            {")
    o.append("                return operation;")
    o.append("            }")
    o.append("        }")
    o.append("")
    o.append("        return null;")
    o.append("    }")
    o.append("}")

    d = [HEADER, "using System.Runtime.CompilerServices;", "using Idrak.Abstraction.Devices.Cpu;", "using Idrak.Abstraction.Operations;", "", "namespace Idrak.Abstraction.Devices;", ""]
    d.append("// Name(...) runs the kernel registered for the device, else its own NameKernel. With RetryOnHost on, the device's own")
    d.append("// kernel of an operation whose default is the host fallback runs under a HostRetry: a DeviceException is reported")
    d.append("// with the operation and the call runs again through NameOnHost, a copy of NameKernel's default body. Composed")
    d.append("// operations need no retry of their own (their parts retry one by one), and operations with no fallback throw.")
    d.append("// A registered kernel is not retried: it is an app's or a plug-in's choice for this device (it may handle some cases")
    d.append("// itself and pass others to the device's kernel or elsewhere), so the dispatcher can't tell which host computation")
    d.append("// matches it or whether its error came from the device at all; its errors reach the caller. An operation the device")
    d.append("// has no kernel of its own for already runs its host fallback: it is not retried (it would only run twice).")
    d.append("public abstract partial class Backend")
    d.append("{")
    for i, (method, op, returns, parameters, docs, default) in enumerate(named):
        arguments = ", ".join(argument(p) for p in split_top(parameters))
        plain = ", ".join(strip_default(p) for p in split_top(parameters))
        call = f"kernel(this{', ' + arguments if arguments else ''})"
        own = f"{method}Kernel({arguments})"
        registered = f"{op}Registered({arguments})"
        if i:
            d.append("")
        # The fast path (no kernel registered for this device and no trace: one field read) is inlined into the call
        # site; the registered path stays out of line.
        runs = f"Runs <see cref=\"Ops.{op}\"/>: the kernel registered for this device (<see cref=\"Kernels.Register\"/>), else <c>{method}Kernel</c>."
        if any("</remarks>" in line for line in docs):
            d.extend(f"    /// {line.replace('</remarks>', f'<para>{runs}</para></remarks>')}".rstrip() for line in docs)
        else:
            d.extend(f"    /// {line}".rstrip() for line in docs)
            d.append(f"    /// <remarks>{runs}</remarks>")
        d.append("    [MethodImpl(MethodImplOptions.AggressiveInlining)]")
        d.append(f"    public {returns} {method}({parameters})")
        d.append("    {")
        if returns == "void":
            d.append("        if (_kernels is null)")
            d.append("        {")
            d.append(f"            {own};")
            d.append("        }")
            d.append("        else")
            d.append("        {")
            d.append(f"            {registered};")
            d.append("        }")
        else:
            d.append(f"        return _kernels is null ? {own} : {registered};")
        d.append("    }")
        d.append("")
        d.append("    [MethodImpl(MethodImplOptions.NoInlining)]")
        d.append(f"    private {returns} {op}Registered({plain})")
        d.append("    {")
        if default == "Host":
            # With RetryOnHost the device's own kernel runs under a HostRetry (see the comment the file starts with).
            ret = "" if returns == "void" else "return "
            host = f"{op}OnHost({arguments})"
            d.append(f"        if (Kernel(OperationIndex.{op}) is OperationKernels.{op} kernel)")
            d.append("        {")
            d.append(f"            {ret}{call};")
            if returns == "void":
                d.append("            return;")
            d.append("        }")
            d.append("")
            d.append(f"        if (!RetryOnHost || !OwnsKernel(OperationIndex.{op}))")
            d.append("        {")
            d.append(f"            {ret}{own};")
            if returns == "void":
                d.append("            return;")
            d.append("        }")
            d.append("")
            d.append(f"        var retry = new HostRetry(Ops.{op});")
            d.append("        try")
            d.append("        {")
            d.append(f"            {ret}{own};")
            d.append("        }")
            d.append("        catch (DeviceException failure)")
            d.append("        {")
            d.append("            retry.Failed(failure);")
            d.append(f"            {ret}{host};")
            d.append("        }")
            d.append("        finally")
            d.append("        {")
            d.append("            retry.End();")
            d.append("        }")
        elif returns == "void":
            d.append(f"        if (Kernel(OperationIndex.{op}) is OperationKernels.{op} kernel)")
            d.append("        {")
            d.append(f"            {call};")
            d.append("        }")
            d.append("        else")
            d.append("        {")
            d.append(f"            {own};")
            d.append("        }")
        else:
            d.append(f"        return Kernel(OperationIndex.{op}) is OperationKernels.{op} kernel ? {call} : {own};")
        d.append("    }")
        if default == "Host":
            # The default body of NameKernel, not virtual: the host fallback whatever the device overrides, counted as
            # a host call of the operation.
            text = bodies[op].replace("new HostCall(this)", f"new HostCall(this, \"{method}\")")
            d.append("")
            d.append(f"    // The host fallback of {op} (the default body of {method}Kernel), for RetryOnHost.")
            d.append(f"    private {returns} {op}OnHost({plain})")
            d.extend(f"    {line}" if j == 0 else line.rstrip() for j, line in enumerate(text.split("\n")))
    d.append("}")

    c = [HEADER, "using Idrak.Abstraction.Devices;", "using Idrak.Abstraction.Operations;", "",
         "namespace Idrak.Abstraction.Testing.Devices;", ""]
    c.append("// Every operation of the device contract, as the conformance check records and replays it.")
    c.append("internal static class OperationCalls")
    c.append("{")
    c.append("    // The operations this file knows; Ops.All.Count when it is current.")
    c.append(f"    public const int Count = {len(named)};")
    c.append("")
    c.append("    // The parameter names of each operation (after the backend), by operation index.")
    c.append("    public static readonly string[][] Parameters =")
    c.append("    [")
    for _method, _op, _returns, parameters, _docs, _default in named:
        names = ", ".join(f'"{parts(p)[2]}"' for p in split_top(parameters))
        c.append(f"        [{names}],")
    c.append("    ];")
    c.append("")
    c.append("    // Registers, for devices of `kind`, a kernel per operation that reports each call to `recorder` with its arguments")
    c.append("    // and runs the device's own kernel (NameKernel).")
    c.append("    public static IDisposable[] Intercept(string kind, CallRecorder recorder) =>")
    c.append("    [")
    for method, op, returns, parameters, _docs, _default in named:
        split = split_top(parameters)
        typed = ", ".join(["Backend backend"] + [strip_default(p) for p in split])
        boxed = ", ".join(recorded(p) for p in split)
        arguments = ", ".join(argument(p) for p in split)
        c.append(f"        Kernels.Register(Ops.{op}, kind, (OperationKernels.{op})(({typed}) =>")
        c.append("        {")
        c.append(f"            var call = recorder.Enter(backend, Ops.{op}, [{boxed}]);")
        c.append("            try")
        c.append("            {")
        if returns == "void":
            c.append(f"                backend.{method}Kernel({arguments});")
            c.append("                CallRecorder.Returned(call, null);")
        else:
            c.append(f"                var result = backend.{method}Kernel({arguments});")
            c.append("                CallRecorder.Returned(call, result);")
            c.append("                return result;")
        c.append("            }")
        c.append("            finally")
        c.append("            {")
        c.append("                recorder.Exit(call);")
        c.append("            }")
        c.append("        })),")
    c.append("    ];")
    c.append("")
    c.append("    // Runs `operation` on `backend` through the dispatcher (Backend.Name(...)) with arguments as Intercept records them;")
    c.append("    // returns what it returns (null for nothing).")
    c.append("    public static object? Invoke(Backend backend, Operation operation, object?[] a)")
    c.append("    {")
    c.append("        IDisposable? cache = null;")
    c.append("        try")
    c.append("        {")
    c.append("            switch (operation.Index)")
    c.append("            {")
    for index, (method, op, returns, parameters, _docs, _default) in enumerate(named):
        arguments = ", ".join(replayed(p, i) for i, p in enumerate(split_top(parameters)))
        c.append(f"                case {index}:")
        if returns == "void":
            c.append(f"                    backend.{method}({arguments});")
            c.append("                    return null;")
        else:
            c.append(f"                    return backend.{method}({arguments});")
    c.append("                default:")
    c.append("                    throw new NotSupportedException($\"{operation} is not known to this version of the testing kit.\");")
    c.append("            }")
    c.append("        }")
    c.append("        finally")
    c.append("        {")
    c.append("            cache?.Dispose();")
    c.append("        }")
    c.append("    }")
    c.append("}")

    OPERATIONS.parent.mkdir(parents=True, exist_ok=True)
    OPERATIONS.write_text("\n".join(o) + "\n", encoding="utf-8", newline="\n")
    DISPATCH.write_text("\n".join(d) + "\n", encoding="utf-8", newline="\n")
    CALLS.parent.mkdir(parents=True, exist_ok=True)
    CALLS.write_text("\n".join(c) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(named)} operations: {OPERATIONS.relative_to(ROOT)}, {DISPATCH.relative_to(ROOT)}, {CALLS.relative_to(ROOT)}")


if __name__ == "__main__":
    generate()
