"""Generates the operation table (plan 9) from the device contract.

Every operation of the device contract is a virtual method `NameKernel` on `Backend`
(src/Idrak.Abstraction/Devices/Backend.cs): the device's own kernel, whose default body is the host fallback. From
those declarations this script writes

  src/Idrak.Abstraction/Operations/Operations.g.cs    a descriptor per operation, its index and its kernel delegate
  src/Idrak.Abstraction/Devices/Backend.Operations.g.cs
                                                      `Name(...)` on Backend, which runs the kernel registered for the
                                                      device (Kernels.Register) or else `NameKernel`

Run it after adding, removing or changing an operation:

  python3 tools/operations/generate.py

The test "operations: ..." in tests/Idrak.Tests/OperationTests.cs fails when the generated files and Backend disagree.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
BACKEND = ROOT / "src/Idrak.Abstraction/Devices/Backend.cs"
OPERATIONS = ROOT / "src/Idrak.Abstraction/Operations/Operations.g.cs"
DISPATCH = ROOT / "src/Idrak.Abstraction/Devices/Backend.Operations.g.cs"

HEADER = """// <auto-generated>
// Generated by tools/operations/generate.py from src/Idrak.Abstraction/Devices/Backend.cs; do not edit.
// </auto-generated>
// Copyright (c) 2026 Ahmed Seada
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

#nullable enable
"""


def split_top(text, sep=","):
    """Splits on `sep` outside brackets, parentheses and generic arguments."""
    parts, depth, current = [], 0, ""
    for ch in text:
        if ch in "([<{":
            depth += 1
        elif ch in ")]>}":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        parts.append(current)
    return [p.strip() for p in parts]


def strip_default(parameter):
    """The parameter without its default value."""
    depth = 0
    for i, ch in enumerate(parameter):
        if ch in "([<{":
            depth += 1
        elif ch in ")]>}":
            depth -= 1
        elif ch == "=" and depth == 0:
            return parameter[:i].strip()
    return parameter


def argument(parameter):
    """The argument passing a parameter on: its name, with ref, out or in."""
    words = strip_default(parameter).split()
    modifier = next((w for w in words if w in ("ref", "out", "in")), None)
    name = words[-1]
    return f"{modifier} {name}" if modifier else name


def operations(source):
    """(name, return type, parameter list) of every `public virtual ... NameKernel(...)` in declaration order."""
    found = []
    for match in re.finditer(r"^    public virtual (.+?) (\w+)Kernel\(", source, re.M):
        start = match.end()
        depth, i = 1, start
        while depth:
            depth += {"(": 1, ")": -1}.get(source[i], 0)
            i += 1
        parameters = " ".join(source[start:i - 1].split())
        found.append((match.group(2), match.group(1), parameters))
    return found


def generate():
    ops = operations(BACKEND.read_text())
    if not ops:
        sys.exit(f"no `public virtual ... NameKernel(` in {BACKEND}")

    # Overloads share the method name; their descriptors and delegates are numbered (MaxPoolBackward, MaxPoolBackward2).
    seen, named = {}, []
    for name, returns, parameters in ops:
        seen[name] = seen.get(name, 0) + 1
        named.append((name, name if seen[name] == 1 else f"{name}{seen[name]}", returns, parameters))

    o = [HEADER, "using Idrak.Abstraction.Devices;", "", "namespace Idrak.Abstraction.Operations;", ""]
    o.append("/// <summary>The index of each operation in a device's kernel slots (see <see cref=\"Ops\"/>).</summary>")
    o.append("internal static class OperationIndex")
    o.append("{")
    for index, (_, op, _, _) in enumerate(named):
        o.append(f"    public const int {op} = {index};")
    o.append("")
    o.append(f"    /// <summary>The number of operations.</summary>")
    o.append(f"    public const int Count = {len(named)};")
    o.append("}")
    o.append("")
    o.append("/// <summary>The kernel delegate of each operation: the device's backend, then the operation's arguments.</summary>")
    o.append("internal static class OperationKernels")
    o.append("{")
    for i, (_, op, returns, parameters) in enumerate(named):
        plain = ", ".join(strip_default(p) for p in split_top(parameters))
        if i:
            o.append("")
        o.append(f"    /// <summary>A kernel for <see cref=\"Ops.{op}\"/>.</summary>")
        o.append(f"    public delegate {returns} {op}(Backend backend{', ' + plain if plain else ''});")
    o.append("}")
    o.append("")
    o.append("internal static partial class Ops")
    o.append("{")
    for _, op, _, _ in named:
        o.append(f"    /// <summary>The operation {op}.</summary>")
        o.append(f"    public static readonly Operation {op} = new(\"{op}\", OperationIndex.{op}, typeof(OperationKernels.{op}));")
        o.append("")
    o.append("    /// <summary>Every operation, by index.</summary>")
    o.append("    public static IReadOnlyList<Operation> All { get; } =")
    o.append("    [")
    for _, op, _, _ in named:
        o.append(f"        {op},")
    o.append("    ];")
    o.append("}")

    d = [HEADER, "using System.Runtime.CompilerServices;", "using Idrak.Abstraction.Operations;", "", "namespace Idrak.Abstraction.Devices;", ""]
    d.append("internal abstract partial class Backend")
    d.append("{")
    for i, (method, op, returns, parameters) in enumerate(named):
        arguments = ", ".join(argument(p) for p in split_top(parameters))
        plain = ", ".join(strip_default(p) for p in split_top(parameters))
        call = f"kernel(this{', ' + arguments if arguments else ''})"
        own = f"{method}Kernel({arguments})"
        registered = f"{op}Registered({arguments})"
        if i:
            d.append("")
        # The fast path (no kernel registered for this device: one field read) is inlined into the call site; the
        # registered path stays out of line.
        d.append(f"    /// <summary>Runs <see cref=\"Ops.{op}\"/>: the kernel registered for this device, else the device's own.</summary>")
        d.append("    [MethodImpl(MethodImplOptions.AggressiveInlining)]")
        d.append(f"    public {returns} {method}({parameters})")
        d.append("    {")
        if returns == "void":
            d.append("        if (_kernels is null)")
            d.append("        {")
            d.append(f"            {own};")
            d.append("        }")
            d.append("        else")
            d.append("        {")
            d.append(f"            {registered};")
            d.append("        }")
        else:
            d.append(f"        return _kernels is null ? {own} : {registered};")
        d.append("    }")
        d.append("")
        d.append("    [MethodImpl(MethodImplOptions.NoInlining)]")
        d.append(f"    private {returns} {op}Registered({plain})")
        d.append("    {")
        if returns == "void":
            d.append(f"        if (Kernel(OperationIndex.{op}) is OperationKernels.{op} kernel)")
            d.append("        {")
            d.append(f"            {call};")
            d.append("        }")
            d.append("        else")
            d.append("        {")
            d.append(f"            {own};")
            d.append("        }")
        else:
            d.append(f"        return Kernel(OperationIndex.{op}) is OperationKernels.{op} kernel ? {call} : {own};")
        d.append("    }")
    d.append("}")

    OPERATIONS.parent.mkdir(parents=True, exist_ok=True)
    OPERATIONS.write_text("\n".join(o) + "\n")
    DISPATCH.write_text("\n".join(d) + "\n")
    print(f"{len(named)} operations: {OPERATIONS.relative_to(ROOT)}, {DISPATCH.relative_to(ROOT)}")


if __name__ == "__main__":
    generate()
