// Copyright (c) 2026 Ahmed Seada
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

namespace Idrak.Backends.Vulkan;

/// <summary>The SPIR-V opcodes the kernel generator emits (numbers from the SPIR-V specification, section 3.52).</summary>
internal enum SpirvOp : ushort
{
    Name = 5,
    MemberName = 6,
    Extension = 10,
    ExtInstImport = 11,
    ExtInst = 12,
    MemoryModel = 14,
    EntryPoint = 15,
    ExecutionMode = 16,
    Capability = 17,
    TypeVoid = 19,
    TypeBool = 20,
    TypeInt = 21,
    TypeFloat = 22,
    TypeVector = 23,
    TypeArray = 28,
    TypeRuntimeArray = 29,
    TypeStruct = 30,
    TypePointer = 32,
    TypeFunction = 33,
    ConstantTrue = 41,
    ConstantFalse = 42,
    Constant = 43,
    Function = 54,
    FunctionEnd = 56,
    Variable = 59,
    Load = 61,
    Store = 62,
    AccessChain = 65,
    Decorate = 71,
    MemberDecorate = 72,
    CompositeExtract = 81,
    ConvertFToU = 109,
    ConvertFToS = 110,
    ConvertSToF = 111,
    ConvertUToF = 112,
    Bitcast = 124,
    SNegate = 126,
    FNegate = 127,
    IAdd = 128,
    FAdd = 129,
    ISub = 130,
    FSub = 131,
    IMul = 132,
    FMul = 133,
    UDiv = 134,
    SDiv = 135,
    FDiv = 136,
    UMod = 137,
    SRem = 138,
    FRem = 140,
    IsNan = 156,
    IsInf = 157,
    LogicalEqual = 164,
    LogicalNotEqual = 165,
    LogicalOr = 166,
    LogicalAnd = 167,
    LogicalNot = 168,
    Select = 169,
    IEqual = 170,
    INotEqual = 171,
    UGreaterThan = 172,
    SGreaterThan = 173,
    UGreaterThanEqual = 174,
    SGreaterThanEqual = 175,
    ULessThan = 176,
    SLessThan = 177,
    ULessThanEqual = 178,
    SLessThanEqual = 179,
    FOrdEqual = 180,
    FOrdNotEqual = 182,
    FOrdLessThan = 184,
    FOrdGreaterThan = 186,
    FOrdLessThanEqual = 188,
    FOrdGreaterThanEqual = 190,
    ShiftRightLogical = 194,
    ShiftRightArithmetic = 195,
    ShiftLeftLogical = 196,
    BitwiseOr = 197,
    BitwiseXor = 198,
    BitwiseAnd = 199,
    Not = 200,
    ControlBarrier = 224,
    MemoryBarrier = 225,
    LoopMerge = 246,
    SelectionMerge = 247,
    Label = 248,
    Branch = 249,
    BranchConditional = 250,
    Return = 253,
}

/// <summary>Storage classes (where a variable lives).</summary>
internal enum StorageClass : uint
{
    Input = 1,
    Workgroup = 4,
    Function = 7,
    PushConstant = 9,
    StorageBuffer = 12,
}

/// <summary>The decorations the generator uses.</summary>
internal enum Decoration : uint
{
    Block = 2,
    ArrayStride = 6,
    BuiltIn = 11,
    Aliased = 20,
    NonWritable = 24,
    Binding = 33,
    DescriptorSet = 34,
    Offset = 35,
}

/// <summary>Built-in compute variables (values of the BuiltIn decoration).</summary>
internal enum BuiltIn : uint
{
    NumWorkgroups = 24,
    WorkgroupId = 26,
    LocalInvocationId = 27,
    GlobalInvocationId = 28,
}

/// <summary>Instructions of the GLSL.std.450 extended set.</summary>
internal enum Glsl : uint
{
    RoundEven = 2,
    Trunc = 3,
    FAbs = 4,
    SAbs = 5,
    Floor = 8,
    Ceil = 9,
    Sin = 13,
    Cos = 14,
    Tanh = 21,
    Pow = 26,
    Exp = 27,
    Log = 28,
    Exp2 = 29,
    Log2 = 30,
    Sqrt = 31,
    InverseSqrt = 32,
    FMin = 37,
    UMin = 38,
    SMin = 39,
    FMax = 40,
    UMax = 41,
    SMax = 42,
    FClamp = 43,
    SClamp = 45,
    Fma = 50,
}
