"""Writes src/Idrak.Cli/Shared/UnicodeTables.cs from the Unicode Character Database.

The idrak tool's right-to-left renderer (src/Idrak.Cli/Shared/Bidi.cs, ArabicShaping.cs) needs four properties the
.NET runtime does not expose: the bidirectional class of every code point, the paired brackets, the mirrored glyphs
and the Arabic joining types, plus the presentation forms each Arabic letter takes. This script reads them from the
UCD files and writes them as C# arrays.

Usage: python make_tables.py UCD_FOLDER [OUT_FILE]
UCD_FOLDER holds DerivedBidiClass.txt (from extracted/), BidiBrackets.txt, BidiMirroring.txt, ArabicShaping.txt and
UnicodeData.txt of one Unicode version (https://www.unicode.org/Public/UCD/latest/ucd/).
"""

import os
import re
import sys

CLASSES = ["L", "R", "AL", "EN", "ES", "ET", "AN", "CS", "NSM", "BN", "B", "S", "WS", "ON",
           "LRE", "LRO", "RLE", "RLO", "PDF", "LRI", "RLI", "FSI", "PDI"]
LONG = {"Left_To_Right": "L", "Right_To_Left": "R", "Arabic_Letter": "AL", "European_Terminator": "ET",
        "Boundary_Neutral": "BN"}


def data_lines(path):
    with open(path, encoding="utf-8") as f:
        for line in f:
            body = line.split("#", 1)[0].strip()
            if body:
                yield [part.strip() for part in body.split(";")]


def code_range(text):
    first, _, last = text.partition("..")
    return int(first, 16), int(last or first, 16)


def version(path):
    with open(path, encoding="utf-8") as f:
        return re.search(r"-(\d+\.\d+\.\d+)\.txt", f.readline()).group(1)


def bidi_classes(folder):
    path = os.path.join(folder, "DerivedBidiClass.txt")
    classes = ["L"] * 0x110000
    # The defaults for unassigned code points (the @missing lines), then the listed values.
    with open(path, encoding="utf-8") as f:
        for line in f:
            match = re.match(r"# @missing: ([0-9A-F.]+); (\w+)", line)
            if match:
                first, last = code_range(match.group(1))
                classes[first:last + 1] = [LONG[match.group(2)]] * (last - first + 1)
    for fields in data_lines(path):
        first, last = code_range(fields[0])
        classes[first:last + 1] = [fields[1]] * (last - first + 1)
    ranges = []
    for cp, cls in enumerate(classes):
        if ranges and ranges[-1][2] == cls:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp, cls])
    return [r for r in ranges if r[2] != "L"]


def main():
    folder = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "..", "src", "Idrak.Cli", "Shared", "UnicodeTables.cs")
    ucd = version(os.path.join(folder, "DerivedBidiClass.txt"))

    ranges = bidi_classes(folder)
    brackets = [(int(f[0], 16), int(f[1], 16), f[2]) for f in data_lines(os.path.join(folder, "BidiBrackets.txt"))]
    mirrors = [(int(f[0], 16), int(f[1], 16)) for f in data_lines(os.path.join(folder, "BidiMirroring.txt"))]
    joining = {}
    for f in data_lines(os.path.join(folder, "ArabicShaping.txt")):
        if f[2] in ("D", "R", "L", "C", "U", "T"):
            joining[int(f[0], 16)] = f[2]

    # Presentation forms: the compatibility decompositions <isolated|final|initial|medial> of one letter, and the
    # lam-alef ligatures (<isolated|final> 0644 ALEF).
    forms = {}
    ligatures = {}
    with open(os.path.join(folder, "UnicodeData.txt"), encoding="utf-8") as f:
        for line in f:
            fields = line.split(";")
            cp = int(fields[0], 16)
            match = re.match(r"<(isolated|final|initial|medial)> ([0-9A-F ]+)$", fields[5])
            if not match or not (0xFB50 <= cp <= 0xFEFF):
                continue
            parts = [int(p, 16) for p in match.group(2).split()]
            if len(parts) == 1 and 0x0600 <= parts[0] <= 0x06FF:
                slot = ["isolated", "final", "initial", "medial"].index(match.group(1))
                entry = forms.setdefault(parts[0], [0, 0, 0, 0])
                if entry[slot] == 0:
                    entry[slot] = cp
            elif 0xFEF5 <= cp <= 0xFEFC:
                entry = ligatures.setdefault(parts[1], [0, 0])
                entry[0 if match.group(1) == "isolated" else 1] = cp

    def rows(items, per_line):
        lines = []
        for i in range(0, len(items), per_line):
            lines.append("        " + " ".join(items[i:i + per_line]))
        return "\n".join(lines)

    joining_ranges = []
    for cp in sorted(joining):
        kind = joining[cp]
        if joining_ranges and joining_ranges[-1][2] == kind and joining_ranges[-1][1] == cp - 1:
            joining_ranges[-1][1] = cp
        else:
            joining_ranges.append([cp, cp, kind])

    text = f"""// Copyright (c) 2026 Ahmed Seada
// Licensed under the Apache License, Version 2.0. See LICENSE in the repository root.

// Generated by tools/unicode/make_tables.py from the Unicode Character Database {ucd} (DerivedBidiClass.txt,
// BidiBrackets.txt, BidiMirroring.txt, ArabicShaping.txt, UnicodeData.txt); do not edit by hand. The data is
// Copyright (c) Unicode, Inc., used under the Unicode License v3 (https://www.unicode.org/license.txt).

namespace Idrak.Cli.Shared;

/// <summary>The Unicode properties the right-to-left renderer needs and .NET does not expose (UCD {ucd}).</summary>
internal static class UnicodeTables
{{
    /// <summary>The Unicode version the tables come from.</summary>
    public const string Version = "{ucd}";

    /// <summary>
    /// Bidirectional classes as (first, last, class) triples in code point order; code points in no range are L.
    /// </summary>
    public static readonly int[] BidiRanges =
    [
{rows([f"0x{a:04X}, 0x{b:04X}, {CLASSES.index(c)}," for a, b, c in ranges], 6)}
    ];

    /// <summary>Paired brackets as (bracket, its pair, 1 for an opening bracket or 0 for a closing one) triples.</summary>
    public static readonly int[] Brackets =
    [
{rows([f"0x{a:04X}, 0x{b:04X}, {1 if t == 'o' else 0}," for a, b, t in brackets], 8)}
    ];

    /// <summary>Mirrored glyphs as (character, its mirror) pairs, for characters shown right to left.</summary>
    public static readonly int[] Mirrors =
    [
{rows([f"0x{a:04X}, 0x{b:04X}," for a, b in mirrors], 10)}
    ];

    /// <summary>
    /// Explicit Arabic joining types as (first, last, type) triples, type one of 'U', 'D', 'R', 'L', 'C', 'T'; other
    /// code points are T when they are nonspacing, enclosing or format characters and U otherwise.
    /// </summary>
    public static readonly int[] Joining =
    [
{rows([f"0x{a:04X}, 0x{b:04X}, '{k}'," for a, b, k in joining_ranges], 6)}
    ];

    /// <summary>
    /// Presentation forms as (letter, isolated, final, initial, medial) quintuples; 0 where the letter has no such form.
    /// </summary>
    public static readonly int[] Forms =
    [
{rows([f"0x{cp:04X}, 0x{f[0]:04X}, 0x{f[1]:04X}, 0x{f[2]:04X}, 0x{f[3]:04X}," for cp, f in sorted(forms.items())], 4)}
    ];

    /// <summary>Lam-alef ligatures as (alef, isolated ligature, final ligature) triples.</summary>
    public static readonly int[] LamAlef =
    [
{rows([f"0x{cp:04X}, 0x{f[0]:04X}, 0x{f[1]:04X}," for cp, f in sorted(ligatures.items())], 4)}
    ];
}}
"""
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"{out}: {len(ranges)} bidi ranges, {len(brackets)} brackets, {len(mirrors)} mirrors, "
          f"{len(joining_ranges)} joining ranges, {len(forms)} letters with forms, {len(ligatures)} lam-alef ligatures")


if __name__ == "__main__":
    main()
