<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Idrak.Samples.HouseApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Idrak\Idrak.csproj" />
    <ProjectReference Include="..\..\src\Idrak.AspNetCore\Idrak.AspNetCore.csproj" />
  </ItemGroup>

</Project>
