<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Idrak\Idrak.csproj" />
    <ProjectReference Include="..\..\src\Idrak.Data\Idrak.Data.csproj" />
    <ProjectReference Include="..\..\src\Idrak.Nlp\Idrak.Nlp.csproj" />
  </ItemGroup>

</Project>
